version: '3.7'

services:
  api-gateway:
    build: ./
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    networks:
      - crayons

networks:
  crayons:
    name: crayons
    driver: bridge
